---
- name: Install Homebrew Packages
  hosts: localhost
  vars:
    cask_packages_to_install:
      - google-chrome
      - visual-studio-code
      - slack
      # - bitwarden # install with mas because brew cask version does not support browser integration
      - notion
      - proxyman
      - rectangle
      - vlc
      # - zoom # has some issue, need to figure out later
      - postman
      - sourcetree
      # - copyq
      # - microsoft-teams
      # - jetbrains-toolbox
      # - flutter
    packages_to_install:
      - mas
      - pyenv
      - rust
      - go
      - node
      - kotlin
      - java
      - gradle
      # - git-lfs
      - git-flow

  tasks:
    - name: Install Homebrew Cask Packages
      include_tasks: cask_package_task.yml
      loop: "{{ cask_packages_to_install }}"
      loop_control:
        loop_var: package_name

    - name: Install Homebrew Packages
      include_tasks: brew_package_task.yml
      loop: "{{ packages_to_install }}"
      loop_control:
        loop_var: package_name
