---
- name: Install Apps from Mac App Store
  hosts: localhost
  vars:
    apps_to_install:
      - name: HashMaker
        id: 509733654
      - name: BitWarden
        id: 1352778147
      - name: Okta Verify
        id: 490179405
      - name: ImageDiff 2
        id: 1602522152

  tasks:
    - name: Install Mac Appstore Apps
      include_tasks: mas_install_task.yml
      loop: "{{ apps_to_install }}"
      loop_control:
        loop_var: app
