---
- name: Install Homebrew Packages
  hosts: localhost
  vars:
    cask_packages_to_install:
      - google-chrome
      - visual-studio-code
      - slack
      # - bitwarden # install with mas because brew cask version does not support browser integration
      - notion
      - proxyman
      - rectangle
      - vlc
      # - zoom # has some issue, need to figure out later
      - postman
      # - copyq # not recommended for new macOS versions
      # - microsoft-teams
      - jetbrains-toolbox
      - flutter
      - android-studio
      - docker
      - dbeaver-community
      # - dotnet-sdk
      - android-platform-tools
      - cursor
      # - firefox
      - fork
      - mongodb-compass
      - orbstack
    packages_to_install:
      - mas
      - pyenv
      - rust
      - go
      - node
      # - kotlin
      # - java
      # - gradle
      - git-flow
      - cocoapods
      - yarn
      # - git-lfs
      - nvm
      - openapi-generator
      - openconnect
      - pnpm
      - swiftlint
      - tmux
      - tree

  tasks:
    - name: Install Homebrew Cask Packages
      include_tasks: cask_package_task.yml
      loop: "{{ cask_packages_to_install }}"
      loop_control:
        loop_var: package_name

    - name: Install Homebrew Packages
      include_tasks: brew_package_task.yml
      loop: "{{ packages_to_install }}"
      loop_control:
        loop_var: package_name
